apiVersion: events.argo.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: example
spec:
  namespace: argo-events
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: example-provider-secret
      key: credentials
